update=Wed 18 Feb 2015 18:11:48 CET
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[eeschema]
version=1
LibDir=
NetFmtName=PcbnewAdvanced
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=/home/luis-diaz/Descargas/Librerias kicad/arduino_shieldsNCL
LibName2=/home/luis-diaz/Descargas/Librerias kicad/dp_devices
LibName3=/home/luis-diaz/Descargas/Librerias kicad/attiny
LibName4=/home/luis-diaz/Descargas/Librerias kicad/freetronics_kicad_library-master/freetronics_schematic
LibName5=power
LibName6=device
LibName7=transistors
LibName8=conn
LibName9=linear
LibName10=regul
LibName11=74xx
LibName12=cmos4000
LibName13=adc-dac
LibName14=memory
LibName15=xilinx
LibName16=special
LibName17=microcontrollers
LibName18=dsp
LibName19=microchip
LibName20=analog_switches
LibName21=motorola
LibName22=texas
LibName23=intel
LibName24=audio
LibName25=interface
LibName26=digital-audio
LibName27=philips
LibName28=display
LibName29=cypress
LibName30=siliconi
LibName31=opto
LibName32=atmel
LibName33=contrib
LibName34=valves
LibName35=/home/luis-diaz/Escritorio/pcbs/librerias/Led_3mm_bigger_pads
LibName36=/home/luis-diaz/Escritorio/pcbs/librerias/led_rgb_addressable
LibName37=/home/luis-diaz/Escritorio/pcbs/librerias/arduino_shieldsNCL
LibName38=/home/luis-diaz/Escritorio/pcbs/librerias/dp_devices
LibName39=/home/luis-diaz/Escritorio/pcbs/librerias/dips-s
LibName40=/home/luis-diaz/Escritorio/pcbs/librerias/attiny
LibName41=/home/luis-diaz/Escritorio/pcbs/librerias/capacitor
LibName42=/home/luis-diaz/Escritorio/pcbs/librerias/switch
[pcbnew]
version=1
LastNetListRead=programador attiny.net
UseCmpFile=1
PadDrill="    0,800000"
PadDrillOvalY="    0,800000"
PadSizeH="    1,900000"
PadSizeV="    1,900000"
PcbTextSizeV="    1,000000"
PcbTextSizeH="    1,000000"
PcbTextThickness="    0,300000"
ModuleTextSizeV="    1,000000"
ModuleTextSizeH="    1,000000"
ModuleTextSizeThickness="    0,150000"
SolderMaskClearance="    0,000000"
SolderMaskMinWidth="    0,000000"
DrawSegmentWidth="    0,200000"
BoardOutlineThickness="    0,150000"
ModuleOutlineThickness="    0,150000"
[pcbnew/libraries]
LibDir=
LibName1=/home/luis-diaz/Escritorio/pcbs/librerias/switch
LibName2=sockets
LibName3=connect
LibName4=discret
LibName5=pin_array
LibName6=divers
LibName7=smd_capacitors
LibName8=smd_resistors
LibName9=smd_crystal&oscillator
LibName10=smd_dil
LibName11=smd_transistors
LibName12=libcms
LibName13=display
LibName14=led
LibName15=dip_sockets
LibName16=pga_sockets
LibName17=valves
LibName18=/home/luis-diaz/Escritorio/pcbs/librerias/zum_module_without_pins
LibName19=/home/luis-diaz/Escritorio/pcbs/librerias/Led_3mm_bigger_pads
LibName20=/home/luis-diaz/Escritorio/pcbs/librerias/BIG_zum_module_without_pins
LibName21=/home/luis-diaz/Escritorio/pcbs/librerias/led_rgb_addressable
LibName22=/home/luis-diaz/Escritorio/pcbs/librerias/zum_module_with_pins
LibName23=/home/luis-diaz/Escritorio/pcbs/librerias/arduino_shields
LibName24=/home/luis-diaz/Escritorio/pcbs/librerias/attiny24_44_84
LibName25=/home/luis-diaz/Escritorio/pcbs/librerias/LD1117V33
LibName26=/home/luis-diaz/Escritorio/pcbs/librerias/dp_devices
LibName27=/home/luis-diaz/Escritorio/pcbs/librerias/dips-s
LibName28=/home/luis-diaz/Escritorio/pcbs/librerias/capacitor
LibName29=/home/luis-diaz/Escritorio/pcbs/logoBQ_Regular
LibName30=/home/luis-diaz/Escritorio/pcbs/logoBQ_library
LibName31=/home/luis-diaz/Escritorio/pcbs/librerias/pads_mod/attiny24-44-84
LibName32=/home/luis-diaz/Escritorio/pcbs/librerias/pads_mod/cap-through_hole
LibName33=/home/luis-diaz/Escritorio/pcbs/librerias/pads_mod/pad1x01
LibName34=/home/luis-diaz/Escritorio/pcbs/librerias/pads_mod/attiny25-45-48
[general]
version=1
